### ISSUE TITLE
TypeError: array_key_exists(): Argument #2 ($array) must be of type array, null given in _eim_required_fields_validate() 

### ISSUE THREAD

**Issue by sudipto68** [backdrop-contrib/eim#3]
I got this error in one of our backdrop site that is using this module. This error happens when we are trying to save a node.
Previously this error was not happening, but recently we have upgraded our PHP version, the previous version was 7.4.3 and the current version is 8.3.12. 
In this new version, we are facing this error. 
Here is the full error message:
`TypeError: array_key_exists(): Argument #2 ($array) must be of type array, null given in _eim_required_fields_validate() (line 137 of /src/modules/eim/eim.module).`

In this line of code if I change this 
`if (!array_key_exists($field, $image_field)) {
      return;
    }`

to this
`if (!is_array($image_field) || !array_key_exists($field, $image_field)) {
      return;
    }`

Then, it is working fine. I think this is for PHP 8+ enforces stricter type checking.

**Comment by stpaultim** [comment]
@sudipto68 Do you know if that change will also work on older versions of PHP?

**Comment by sudipto68** [comment]
@stpaultim Yes. Because In the old version, this was showing as a warning. The code change I provided is just for more better type check. If I use this on the old (7.4 version) then there also it works and the warning gone.

**Comment by stpaultim** [comment]
@sudipto68 Let's submit a PR!

**Comment by laryn** [comment]
Thank you @sudipto68 and @stpaultim -- do you find this module still valuable? Is there any conflict with core -- e.g. https://github.com/backdrop-contrib/eim/issues/2 ?

**Comment by stpaultim** [comment]
@laryn we are using this on a site that you built, so to be honest I'm not sure how helpful it has been. We only noticed the module was there, when we upgraded PHP and we started getting errors when trying to do specific things. 

I'll have to look closer at the module and what it's doing to be clear on how important the module is or if we still need it.
